# Generated by Django 4.2.20 on 2025-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('reminder', models.CharField(max_length=250, verbose_name='Нагадування')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Нотатка',
                'verbose_name_plural': 'Нотатки',
            },
        ),
    ]
