# Generated by Django 4.2.20 on 2025-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='notes.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категорія'),
        ),
    ]
