# Generated by Django 4.2.20 on 2025-03-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_category_remove_articles_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
